# Generated by Django 3.0.5 on 2020-04-04 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
