# Generated by Django 3.0.5 on 2020-04-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200404_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='trends',
        ),
        migrations.AddField(
            model_name='trend',
            name='keyword',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Keyword'),
        ),
    ]
