# Generated by Django 3.0.5 on 2020-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200405_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Keyword'),
        ),
    ]
